# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#

defaults: &defaults
  working_directory: ~
  docker:
    - image: circleci/ruby:2.5.1-browsers

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: install eb cli
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade

      - persist_to_workspace:
          root: workspace
          paths:
            - repo

  deploy-staging:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace/repo
      - run:
          name: deploy staging
          command: eb deploy hipaa-sample-staging

  deploy-demo:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace/repo
    steps:
      - run:
          name: deploy staging
          command: eb deploy hipaa-sample-demo

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy-staging:
          requires:
            - build
      - deploy-demo:
          type: approval
          requires:
           - deploy-staging
#  deploy-demo:
#    jobs:
#      - deploy-demo:
#          requires:
#            - tag-for-prod-deploy
#          filters:
#            tags:
#              only: /^deploy-v.*/
