# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: chartsockcfa/hipaa-sample-ci:initial

version: 2
jobs:
  deploy-staging:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: deploy staging
          command: eb deploy hipaa-sample-staging


  tag-as-promoted:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: tag as promoted
          command: git tag workflow-$CIRCLE_WORKFLOW_ID; git push --tags

  deploy-demo:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: deploy demo
          command: eb deploy hipaa-sample-demo

  deploy-production:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: deploy production2
          command: eb deploy hipaa-sample-production2

workflows:
  version: 2
  build:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only:
                - master
      - approve-for-production:
          type: approval
          requires:
            - deploy-staging
      - tag-as-promoted:
          requires:
            - approve-for-production
      - deploy-demo:
          requires:
            - tag-as-promoted
      - deploy-production:
          requires:
            - tag-as-promoted
